---
- name: Init Tunning
  debug:
        msg: "Init Tuning"

- name: Set Overcommit memory
  shell: "echo vm.overcommit_memory = 2 >> /etc/sysctl.conf"

- name: Set Overcommit ratio
  shell: "echo vm.overcommit_ratio = 100 >> /etc/sysctl.conf"

- name: Fixing misstyping swappiness
  shell: "sed -i 's/vm.swappines =/swappiness =/g' /etc/sysctl.conf"

- name: Set max map count
  shell: "sysctl -w vm.max_map_count=131072"

- name: Set Overcommit
  shell: "sysctl -p"
